# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:18.04

ENV LANG   "en_US.utf8"
ENV LC_ALL "en_US.utf8"
ENV SHELL  "/bin/bash"
ENV TZ     "UTC"

# Hotfix for systemd
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y systemd \
    && find /lib/systemd/system/sysinit.target.wants/ -name "systemd-tmpfiles-setup.service" -delete \
    && rm -f /lib/systemd/system/multi-user.target.wants/* \
    && rm -f /etc/systemd/system/*.wants/* \
    && rm -f /lib/systemd/system/local-fs.target.wants/* \
    && rm -f /lib/systemd/system/sockets.target.wants/*udev* \
    && rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
    && rm -f /lib/systemd/system/basic.target.wants/* \
    && rm -rf /var/lib/apt/lists/*

# Hotfix for en_US.utf8 locale
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y locales \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV OPENJDK_RELEASE              "{{ openjdk_release }}"
ENV JIRA_VERSION                 "{{ jira_version }}"
ENV JIRA_OWNER                   "{{ jira_owner }}"
ENV JIRA_GROUP                   "{{ jira_group }}"
ENV JIRA_HOME                    "{{ jira_home }}"
ENV JIRA_CATALINA                "{{ jira_catalina }}"
ENV JVM_MINIMUM_MEMORY           "{{ jira_jvm_minimum_memory }}"
ENV JVM_MAXIMUM_MEMORY           "{{ jira_jvm_maximum_memory }}"
ENV CATALINA_CONNECTOR_PROXYNAME "{{ jira_catalina_connector_proxyname }}"
ENV CATALINA_CONNECTOR_PROXYPORT "{{ jira_catalina_connector_proxyport }}"
ENV CATALINA_CONNECTOR_SCHEME    "{{ jira_catalina_connector_scheme }}"
ENV CATALINA_CONNECTOR_SECURE    "{{ jira_catalina_connector_secure }}"
ENV CATALINA_CONTEXT_PATH        "{{ jira_catalina_context_path }}"
ENV JVM_SUPPORT_RECOMMENDED_ARGS "{{ jira_jvm_support_recommended_args }}"
ENV SESSION_TIMEOUT              "300"
ENV PATH                         "$PATH:$JIRA_CATALINA/bin"

VOLUME  $JIRA_HOME
WORKDIR $JIRA_HOME

EXPOSE 8005
EXPOSE 8080

ENTRYPOINT [ "tini", "-g", "--", "docker-entrypoint.sh" ]
CMD        [ "start-jira.sh", "-fg" ]

# Explicitly set system user UID/GID
RUN set -ex \
    && groupadd -r $JIRA_OWNER \
    && useradd -r -g $JIRA_GROUP -d $JIRA_HOME -M -s /usr/sbin/nologin $JIRA_OWNER
